// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUeoTlslUtZNspaBLEQzISoMNXHUjaHrY',
    appId: '1:833957864007:web:2381da42609002b1984762',
    messagingSenderId: '833957864007',
    projectId: 'hrms-b2fce',
    authDomain: 'hrms-b2fce.firebaseapp.com',
    storageBucket: 'hrms-b2fce.firebasestorage.app',
    measurementId: 'G-NFBG2K4GBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvo58_VAkfgEk6SVgwgInel4x38Sm6mew',
    appId: '1:833957864007:android:0e9dc30e84dde953984762',
    messagingSenderId: '833957864007',
    projectId: 'hrms-b2fce',
    storageBucket: 'hrms-b2fce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6mYQX0wMYMUZiMSfIdQlVto5Um3Qh_d4',
    appId: '1:833957864007:ios:4017f9eb42d4290f984762',
    messagingSenderId: '833957864007',
    projectId: 'hrms-b2fce',
    storageBucket: 'hrms-b2fce.firebasestorage.app',
    iosBundleId: 'com.example.hrms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6mYQX0wMYMUZiMSfIdQlVto5Um3Qh_d4',
    appId: '1:833957864007:ios:4017f9eb42d4290f984762',
    messagingSenderId: '833957864007',
    projectId: 'hrms-b2fce',
    storageBucket: 'hrms-b2fce.firebasestorage.app',
    iosBundleId: 'com.example.hrms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUeoTlslUtZNspaBLEQzISoMNXHUjaHrY',
    appId: '1:833957864007:web:35c7c725d37c259d984762',
    messagingSenderId: '833957864007',
    projectId: 'hrms-b2fce',
    authDomain: 'hrms-b2fce.firebaseapp.com',
    storageBucket: 'hrms-b2fce.firebasestorage.app',
    measurementId: 'G-TKFFK6VXMR',
  );
}
